import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import Navigation from "../components/Navigation/Navigation";
import HeroSection from "../components/HeroSection/HeroSection";
import SectionTwo from "../components/SectionTwo/SectionTwo";
import SectionThree from "../components/SectionThree/SectionThree";
import SectionFour from "../components/SectionFour/SectionFour";
import SectionFive from "../components/SectionFive/SectionFive";
import SectionSix from "../components/SectionSix/SectionSix";
import SectionSeven from "../components/SectionSeven/SectionSeven";
import SectionEight from "../components/SectionEight/SectionEight";
import SectionNine from "../components/SectionNine/SectionNine";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";

export default function Home() {

  function ctaAction(event: React.MouseEvent) {
    event.preventDefault();
    console.log(event);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <Navigation />
        <HeroSection
          heading={
            <h1 className={ `hero_heading w-[25ch] text-white` }>
              Trade Your Cryptocurrency And{ " " }
              <span className={ `text-accent-2` }> Gift Cards</span> At High
              Rates!
            </h1>
          }
          subheading={
            <p className={ `hero_subheading text-white` }>
              We trade cryptocurrency, gift cards and electronic assets.
            </p>
          }
          ctaText={ `Signup Now!` }
          ctaAction={ ctaAction }
        />
      </Header>
      <main className={ `${styles.main} max-w-screen-xl mx-auto` }>
        <SectionTwo />
        <SectionThree />
        <SectionFour />
        <SectionFive />
        <SectionSix />
        <SectionSeven />
        <SectionEight />
        <SectionNine />
      </main>
      <Footer />
    </>
  );
}
