import Head from "next/head";
import React, { useRef, useEffect, useLayoutEffect } from "react";
import gsap from "gsap";
import useIntersectionObserver from "../../hooks/useIntersectionObserver";

import Header from "../../components/Header/Header";
import Navigation from "../../components/Navigation/Navigation";
import HeroSection from "../../components/HeroSection/HeroSection";
import Container from "../../components/Container/Container";

import sectionOneImage from "../../assets/AboutPage/section_one/hero.png";
import sectionTwoImage_1 from "../../assets/AboutPage/section_two/img_1.png";
import sectionTwoImage_2 from "../../assets/AboutPage/section_two/img_2.png";
import sectionThreeImage_1 from "../../assets/AboutPage/section_three/img_1.png";
import sectionThreeImage_2 from "../../assets/AboutPage/section_three/img_2.png";
import sectionThreeImage_3 from "../../assets/AboutPage/section_three/img_3.png";
import { BsFlag } from "react-icons/bs";
import SectionNine from "../../components/SectionNine/SectionNine";
import Footer from "../../components/Footer/Footer";

function index() {
  const rootElement = useRef<HTMLDivElement | null>(null)
  const [element_1, isElement1Visible] = useIntersectionObserver({ rootMargin: "-200px" });
  const [element_2, isElement2Visible] = useIntersectionObserver({ rootMargin: "-200px" });
  const [element_3, isElement3Visible] = useIntersectionObserver({ rootMargin: "-200px" });
  const [element_4, isElement4Visible] = useIntersectionObserver({ rootMargin: "-200px" });

  const timeline_1 = useRef<GSAPTimeline | null>(null);
  const timeline_2 = useRef<GSAPTimeline | null>(null);
  const timeline_3 = useRef<GSAPTimeline | null>(null);
  const timeline_4 = useRef<GSAPTimeline | null>(null);


  useLayoutEffect(() => {
    const gctx = gsap.context(() => {
      timeline_1.current = gsap.timeline({ paused: true, defaults: { ease: 'expo.out', duration: 0.5 } });
      timeline_2.current = gsap.timeline({ paused: true, defaults: { ease: 'expo.out', duration: 0.5 } });
      timeline_3.current = gsap.timeline({ paused: true, defaults: { ease: 'expo.out', duration: 0.5 } });
      timeline_4.current = gsap.timeline({ paused: true, defaults: { ease: 'expo.out', duration: 0.5 } });

      timeline_1.current
        .fromTo('.section_1_content_wrapper > .column_2 > div', { xPercent: 50, opacity: 0 }, { xPercent: 0, opacity: 1 })
        .fromTo('.section_1_content_wrapper > .column_1 > *', { yPercent: 50, opacity: 0 }, { yPercent: 0, opacity: 1, stagger: 0.3 })
      timeline_2.current
        .fromTo('.section_2_content_wrapper > .column_1 > div', { scale: 0.5, opacity: 0 }, { scale: 1, opacity: 1, stagger: 0.3 })
        .fromTo('.section_2_content_wrapper > .column_2 > *', { yPercent: 50, opacity: 0 }, { yPercent: 0, opacity: 1, stagger: 0.3 })
      timeline_3.current
        .fromTo('.section_3_content_wrapper > .column_2 > div > div', { scale: 0.5, opacity: 0 }, { scale: 1, opacity: 1, stagger: 0.3 })
        .fromTo('.section_3_content_wrapper > .column_1 > *', { yPercent: 50, opacity: 0 }, { yPercent: 0, opacity: 1, stagger: 0.3 })
      timeline_4.current
        .fromTo('.section_4_content_wrapper > h2', { yPercent: 50, opacity: 0 }, { yPercent: 0, opacity: 1 })
        .fromTo('.section_4_content_wrapper > div > div > .orb', { scale: 0.5, opacity: 0 }, { scale: 1, opacity: 1, ease: "elastic.out(1.5, 0.5)", stagger: 0.3 })

    }, rootElement);

    return () => {
      gctx.clear()
      gctx.revert();
      timeline_1.current!.clear();
      timeline_2.current!.clear();
      timeline_3.current!.clear();
      timeline_4.current!.clear();
    };
  }, []);

  useEffect(() => {
    if (isElement1Visible) {
      timeline_1.current!.play();
    }
    if (isElement2Visible) {
      timeline_2.current!.play();
    }
    if (isElement3Visible) {
      timeline_3.current!.play();
    }
    if (isElement4Visible) {
      timeline_4.current!.play();
    }

  }, [isElement1Visible, isElement2Visible, isElement3Visible, isElement4Visible])


  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
      </Head>
      <Header>
        <Navigation />
        <HeroSection heading={ <h1 className={ `hero_heading text-white` }>About Us</h1> } subheading={ <p className={ `hero_subheading text-white` }>
          We trade cryptocurrency, gift cards and electronic assets.</p> } />
      </Header>
      <main ref={ rootElement } className={ `w-full h-fit min-h-screen  max-w-screen-lg mx-auto flex flex-col items-center justify-start gap-20` }>
        <Container>
          <div ref={ element_1 } className={ `section_1_content_wrapper w-full h-fit flex flex-row items-center justify-between` }>
            <div className={ `column_1 flex-1 w-full h-fit text-left` }>
              <p>ABOUT US</p>
              <h2>From The Management</h2>
              <p>
                Welcome to PayBuyMax Tech, your number one source for trading
                cryptocurrency, gift cards and more. We're dedicated to
                providing you the very best of trading, with an emphasis on
                integrity, passion and professionalism.
              </p>
              <p>
                Founded in 2015 by two friends and colleagues Engr Okenwa & Engr
                Okolo. PayBuyMax Tech has come a long way from its beginnings.
                Engr. Okolo first started out trading bitcoins and gift cards as
                a hobby in his home, his passion has remained to make trading
                easy and enable free banking for all.
              </p>
              <p>
                We hope you enjoy our services as much as we enjoy offering them
                to you. If you have any questions or comments, please don't
                hesitate to contact us.
              </p>
              <p>
                Sincerely, <br /> PayBuyMax Tech Mgt.
              </p>
            </div>
            <div className={ `column_2 flex-1 w-full h-fit` }>
              <div className={ `aspect-square w-full h-full` }>
                <img
                  src={ sectionOneImage.src }
                  alt=""
                  className={ `w-full h-full object-contain` }
                />
              </div>
            </div>
          </div>
        </Container>
        <Container>
          <div ref={ element_2 } className={ `section_2_content_wrapper w-full h-fit flex flex-row items-center justify-between gap-8` }>
            <div className={ `column_1 flex-1 relative z-0 aspect-square w-[50%] h-auto` }>
              <div className={ ` absolute z-[1] top-[50%] left-[50%] -translate-x-[50%] -translate-y-[50%] w-full` }>
                <img
                  src={ sectionTwoImage_1.src }
                  alt=""
                  className={ `w-full h-full object-contain` }
                />
              </div>
              <div className={ `absolute z-[2] top-[50%] left-[50%] -translate-x-[50%] -translate-y-[50%] w-[90%]` }>
                <img
                  src={ sectionTwoImage_2.src }
                  alt=""
                  className={ `w-full h-full object-contain` }
                />
              </div>
            </div>
            <div className={ `column_2 flex-1 w-[50%] h-fit` }>
              <p>WHAT WE DO</p>
              <h2>Trading Cryptocurrency</h2>
              <p>
                PayBuyMax Tech offer competitive rates for cryptocurrency (BTC,
                USDT, ETH,LTC, BNB, DOGE ETC) and electronic assets(gift cards,
                zelle, cashapp, greendot, Lille, sofi, money lion, EDD spending,
                aspiration, paypal, Skrill, neteller etc) in Nigeria and this is
                possible because we are licensed to trade on two international
                forex broker platforms.
              </p>
              <p>
                Paybuymax is into trading of cryptocurrency, giftcards and
                electronic assets.
              </p>
            </div>
          </div>
        </Container>
        <Container>
          <div ref={ element_3 } className={ `section_3_content_wrapper w-full h-fit flex flex-row items-center justify-between gap-8` }>
            <div className={ `column_1 flex-1 w-full h-fit` }>
              <p>WHY TRADE WITH US</p>
              <h2>Best Trading Experience</h2>
              <p>
                As we strive to establish our company as the best name in the
                cryptocurrency market we adopt Integrity, passion and
                professionalism as our watchword.
              </p>
              <p>This concurrently implies:</p>
              <div
                className={ `w-full h-fit flex flex-col items-center justify-start gap-4` }
              >
                <div
                  className={ `w-full h-fit flex flex-row items-center justify-start gap-4` }
                >
                  <div
                    className={ `flex-1 flex flex-row items-center justify-start gap-4` }
                  >
                    <span>
                      <BsFlag />
                    </span>
                    <span>Instant funding of account on request</span>
                  </div>
                  <div
                    className={ `flex-1 flex flex-row items-center justify-start gap-4` }
                  >
                    <span>
                      <BsFlag />
                    </span>
                    <span>We have more than enough Bitcoin to go around</span>
                  </div>
                </div>

                <div
                  className={ `w-full h-fit flex flex-row items-center justify-start gap-4` }
                >
                  <div
                    className={ `flex-1 flex flex-row items-center justify-start gap-4` }
                  >
                    <span>
                      <BsFlag />
                    </span>
                    <span>Bonus And Incentives</span>
                  </div>
                  <div
                    className={ `flex-1 flex flex-row items-center justify-start gap-4` }
                  >
                    <span>
                      <BsFlag />
                    </span>
                    <span>Fast payment is assured</span>
                  </div>
                </div>

                <div
                  className={ `w-full h-fit flex flex-row items-center justify-start gap-4` }
                >
                  <span>
                    <BsFlag />
                  </span>
                  <span>
                    emaining highly Liquidated by keeping our business
                    diversified by trading Forex, Real estate, Purchasing Bonds
                    and proffering Lending Services
                  </span>
                </div>
              </div>
            </div>
            <div className={ `column_2 flex-1 w-full h-fit` }>
              <div className={ `aspect-square w-full h-auto flex flex-row items-center justify-center gap-8` }>
                <div className={ `flex-1 relative h-full` }>
                  <div
                    className={ `absolute bottom-[10%] aspect-square w-[100px] h-auto bg-accent rounded-md` }
                  ></div>
                </div>
                <div className={ `flex-1 relative h-full` }>
                  <div className={ `w-full h-fit my-4` }>
                    <img
                      src={ sectionThreeImage_1.src }
                      alt=""
                      className={ `w-full h-full object-contain` }
                    />
                  </div>
                  <div className={ `w-full h-fit my-4` }>
                    <img
                      src={ sectionThreeImage_2.src }
                      alt=""
                      className={ `w-full h-full object-contain` }
                    />
                  </div>
                </div>
                <div className={ `flex-1 relative h-full` }>
                  <div
                    className={ `aspect-[1/1.5] w-[100px] h-auto bg-accent-2 rounded-md` }
                  ></div>
                  <div className={ `w-full h-fit my-4` }>
                    <img
                      src={ sectionThreeImage_3.src }
                      alt=""
                      className={ `w-full h-full object-contain` }
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Container>
        <Container>
          <div ref={ element_4 } className={ `section_4_content_wrapper w-full h-fit text-center` }>
            <h2>Mission, Vission & Core Values</h2>
            <div className={ `w-full h-fit flex flex-col items-center justify-center` }>
              <div className={ `relative w-[600px] h-[600px]` }>
                <div className={ `orb absolute -translate-x-[50%] -translate-y-[50%] top-[30%] left-[50%] aspect-square w-[250px] h-auto flex flex-row items-center justify-center text-center bg-orange-600 rounded-full text-white group/mission hover:z-10` }>
                  <h3>MISSION</h3>
                  <p
                    className={ `absolute top-[50%] left-[50%] -translate-x-[50%] -translate-y-[50%] aspect-square w-[350px] scale-0 h-auto p-4 flex flex-col items-center justify-center font-semibold bg-white/80 backdrop-blur-md text-accent rounded-full border-2 border-accent overflow-hidden group-hover/mission:scale-100 transition-all` }
                  >
                    To be the leading exchange in Nigeria, offering our services
                    at optimum price while availing our customers the benefit of
                    enjoying instant and seamless payment.
                  </p>
                </div>
                <div className={ `orb absolute -translate-x-[50%] -translate-y-[50%] top-[70%] left-[25%] aspect-square w-[250px] h-auto flex flex-row items-center justify-center text-center bg-green-600 rounded-full text-white group/values hover:z-10` }>
                  <h3>CORE VALUES</h3>
                  <p
                    className={ `absolute top-[50%] left-[50%] -translate-x-[50%] -translate-y-[50%] aspect-square w-[350px] scale-0 h-auto p-4 flex flex-col items-center justify-center font-semibold bg-white/80 backdrop-blur-md text-accent rounded-full border-2 border-accent overflow-hidden group-hover/values:scale-100 transition-all` }
                  >
                    To add value, sensitize and ensure customers are financially
                    independent.
                  </p>
                </div>
                <div className={ `orb absolute -translate-x-[50%] -translate-y-[50%] top-[70%] left-[75%] aspect-square w-[250px] h-auto flex flex-row items-center justify-center text-center bg-yellow-600 rounded-full text-white group/vission hover:z-10` }>
                  <h3>VISSION</h3>
                  <p
                    className={ `absolute top-[50%] left-[50%] -translate-x-[50%] -translate-y-[50%] aspect-square w-[350px] scale-0 h-auto p-4 flex flex-col items-center justify-center font-semibold bg-white/80 backdrop-blur-md text-accent rounded-full border-2 border-accent overflow-hidden group-hover/vission:scale-100 transition-all` }
                  >
                    Integrity <br /> Passion <br /> Professionalism
                  </p>
                </div>
              </div>
            </div>
          </div>
        </Container>
        <SectionNine />
      </main>
      <Footer />
    </>
  );
}

export default index;
