import Head from "next/head";
import Navigation from "../components/Navigation";
import AnnouncementBar from "../components/AnnouncementBar";
import HeroSection from "../components/HeroSection";
import SectionTwo from "../components/SectionTwo";
import SectionThree from "../components/SectionThree";
import SectionFour from "../components/SectionFour";
import SectionFive from "../components/SectionFive";
import SectionSix from "../components/SectionSix";
import logo from "../assets/brand_logos/primary_logo2.png";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnnouncementBar />
      <Navigation />
      <main className="flex flex-col items-center justify-start">
        <HeroSection />
        <SectionTwo />
        <SectionThree />
        <SectionFour />
        <SectionFive />
        <SectionSix />
      </main>
      <footer className="w-[75%] h-fit p-16 mx-auto bg-primary flex flex-row items-start justify-between text-secondary">
        <div>
          <img src={logo.src} alt="" className="w-[150px] aspect-[3/1.5]" />
        </div>
        <div className="flex flex-col items-start justify-start gap-4">
          <Link href={"#"} className="text-accent font-semibold">
            OUR PORTFOLIO
          </Link>
          <ul>
            <li>Home</li>
            <li>About</li>
            <li>Our Work</li>
          </ul>
        </div>
        <div className="flex flex-col items-start justify-start gap-4">
          <Link href={"#"} className="text-accent font-semibold">
            OUR SERVICES
          </Link>
          <ul>
            <li>Marketing</li>
            <li>Development</li>
            <li>Branding</li>
          </ul>
        </div>
        <div className="flex flex-col items-start justify-start gap-4">
          <Link href={"#"} className="text-accent font-semibold">
            CONTACT
          </Link>
          <ul>
            <li>Email</li>
            <li>LinkedIn</li>
            <li>Instagram</li>
            <li>Twitter</li>
          </ul>
        </div>
        <div className="flex flex-col items-start justify-start gap-4">
          <h5>Let's Make Your Business Fly!</h5>
          <div className="w-fit h-fit px-1 py-1 flex items-center justify-between gap-4 rounded-full bg-accent">
            <input
              type="email"
              name="user_email"
              className="bg-transparent text-slate-900 focus:bg-tranparent"
              placeholder="Enter Your Email Here..."
            />
            <button className="px-2 py-1 font-semibold bg-primary text-secondary rounded-full">
              SUBMIT!
            </button>
          </div>
        </div>
      </footer>
    </>
  );
}
